baseURL = 'https://thebookies.club/'
languageCode = 'en-us'
title = 'The Bookies Club'
theme = 're-terminal'
enableEmoji = true

pagination.pagerSize = 5

[outputs]
home = ["HTML", "RSS"]

[params]
  # section to list on the home page
  contentTypeName = "posts"

  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  seriesOpenByDefault = true
  seriesMaxItems = 0

[params.twitter]
  creator = ""
  site = ""

[languages]
  [languages.en.params]
    languageName = "English"
    title = "The Bookies Club"
    subtitle = "A pair of book lovers sharing their thoughts."
    owner = ""
    keywords = "books, book reviews, reading"
    copyright = ""
    menuMore = "Show more"
    readMore = "Continue Reading"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "The Bookies Club"
      logoHomeLink = "/"

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
      weight = 10
    [[languages.en.menu.main]]
      identifier = "rules"
      name = "Rules"
      url = "/rules"
      weight = 11
    [[languages.en.menu.main]]
      identifier = "resources"
      name = "Resources"
      url = "/resources"
      weight = 12
    [[languages.en.menu.main]]
      identifier = "archive"
      name = "Archive"
      url = "/archives"
      weight = 14
    [[languages.en.menu.main]]
      identifier = "search"
      name = "Search"
      url = "/search"
      weight = 15
