baseURL = 'https://thebookies.club/'
languageCode = 'en-us'
title = 'The Bookies Club'
theme = 'papermod'
enableEmoji = true

[outputs]
home = [
    "HTML",
    "RSS",
    "JSON",
]

[params]
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
ShowFullTextinRSS = true

[params.homeInfoParams]
Title = ":books: Let's read together."
Content = """
We are a group of book lovers who enjoy action, adventure, and mystery in
particular. While you're here, check out our [Rules](/rules), our great list of
[Resources](/resources), and the list of [the books we've read](/archives). If
you'd like to join, fill out a spot on our [Waitlist](https://files.thelinuxcast.org/index.php/apps/forms/s/yxEGk4ssJyr65yZPk8KML7Kf).
"""

[[params.socialIcons]]
name = "github"
title = "GitHub"
url = "https://github.com/the-bookies-club"

[[params.socialIcons]]
name = "rss"
title = "RSS"
url = "/index.xml"

[languages.en.menu]
main = [
    { name = "About", url = "about/", weight = 10},
    { name = "Rules", url = "rules/", weight = 11},
    { name = "Resources", url = "resources/", weight = 12 },
    { name = "Waitlist", url = "https://files.thelinuxcast.org/index.php/apps/forms/s/yxEGk4ssJyr65yZPk8KML7Kf", weight = 13 },
    { name = "Archive", url = "archives/", weight = 14},
    { name = "Search", url = "search/", weight = 15 },
]

