baseURL = 'https://thebookies.club/'
languageCode = 'en-us'
title = 'The Bookies Club'
theme = 'papermod'
enableEmoji = true

[outputs]
home = [
    "HTML",
    "RSS",
    "JSON",
]

[params]
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
ShowFullTextinRSS = true

[params.homeInfoParams]
Title = ":books: Let's read together."
Content = """
We are a group of book lovers who enjoy action, adventure, and mystery in particular.
"""

[[params.socialIcons]]
name = "github"
title = "GitHub"
url = "https://github.com/the-bookies-club"

[[params.socialIcons]]
name = "rss"
title = "RSS"
url = "https://thebookies.club/index.xml"

[languages.en.menu]
main = [
    { name = "About", url = "about/", weight = 10},
    { name = "Rules", url = "rules/", weight = 11},
    { name = "Search", url = "search/", weight = 13 },
    { name = "Archive", url = "archives/", weight = 12},
]

